Repository aquasecurity/kube-bench, pull requests merged in 2019-08, with the labels that each got.

#377 Fix version command failing because of missing config file it does not need.
  cmd/common.go
  cmd/root.go
Labels: bug

#383 Update config.yaml to add Azure AKS file locations for kubelet
  cfg/config.yaml
Labels: enhancement

#385 Updated version support
  README.md
Labels: documentation
