Repository aquasecurity/kube-bench, pull requests merged in 2020-09, with the labels that each got.

#687 Add a trailing slash to find directory path
  cfg/cis-1.5/master.yaml
Labels: fix benchmark

#691 docs: more clarification on output states
  README.md
Labels: documentation

#703 Set actualResult
  check/test.go
Labels: bug
